version: '3.8'
services:
  mysql:
    image: mysql:8.0.31
    restart: always
    command: mysqld --default_authentication_plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: wordpress
    ports:
      - 3306:3306
    networks:
      - wordpress-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: docker
    networks:
      - wordpress-network
 
  wordpress:
    image: wordpress:6.0.2
    restart: always
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: docker
    ports:
      - 80:80
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge

volumes:
  db_data:
  wp_data:
